name: testing-cli
on:
  workflow_dispatch:

  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'master'
jobs:
  run-cli-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository code
      - uses: actions/checkout@v3
      # Configure python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Setup the CRMint test environment
      - name: Setup CLI
        run: pip install ./cli[test]
      # Run the tests
      - name: Run the tests
        working-directory: cli
        run: pytest --cov=. --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: cli
          fail_ci_if_error: false
          flags: cli
  install-cli-test:
    runs-on: ubuntu-latest
    env:
      CRMINT_CLI_DOCKER_IMAGE: crmint/cli:latest
      CRMINT_HOME: ${{ github.workspace }}
      # Fakes a gcloud config path locally
      CLOUDSDK_CONFIG: ${{ github.workspace }}/.config/gcloud
    steps:
      # Checkout repository code
      - uses: actions/checkout@v3
      # Build the CLI wrapper image
      - name: Build CLI image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./cli/Dockerfile
          push: false
          tags: crmint/cli:latest
      # Install the CLI using our install script
      - name: Install CLI
        run: source scripts/install.sh
